language: python

python:
  - "3.4_with_system_site_packages"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq python3-gi gir1.2-gtk-3.0 libnotify-bin

install:
  - pip install -r requirements.txt
  - pip install --upgrade .

script:
  - pytest
